# Generated by Django 6.0.4 on 2026-05-04 11:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.booking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('advance', 'Avance'), ('full', 'Paiement total')], default='advance', max_length=20),
        ),
    ]
