# Generated by ChatGPT on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking_customer_phone_magiclogintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='damaged_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='lost_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='available_quantity',
            field=models.IntegerField(default=0),
        ),
    ]

