# Generated by Django 6.0.6 on 2026-06-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_code_fields_to_booking_and_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
