# Generated by Django 6.0.6 on 2026-06-11 14:48

from django.db import migrations
from django.utils import timezone


def populate_codes(apps, schema_editor):
    Booking = apps.get_model('api', 'Booking')
    Payment = apps.get_model('api', 'Payment')

    # Populate booking codes
    bookings = Booking.objects.all().order_by('created_at')
    booking_month_counts = {}
    for booking in bookings:
        if not booking.code:
            month_key = (booking.created_at.year, booking.created_at.month)
            count = booking_month_counts.get(month_key, 0) + 1
            booking_month_counts[month_key] = count
            month_year = booking.created_at.strftime('%m%y')
            booking.code = f"LBR{month_year}{count:04d}"
            booking.save(update_fields=['code'])

    # Populate payment codes
    payments = Payment.objects.all().order_by('created_at')
    payment_month_counts = {}
    for payment in payments:
        if not payment.code:
            month_key = (payment.created_at.year, payment.created_at.month)
            count = payment_month_counts.get(month_key, 0) + 1
            payment_month_counts[month_key] = count
            month_year = payment.created_at.strftime('%m%y')
            payment.code = f"LBP{month_year}{count:04d}"
            payment.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_payment_created_at'),
    ]

    operations = [
        migrations.RunPython(populate_codes),
    ]
