# Generated by Django 6.0.6 on 2026-06-11 15:15

from django.db import migrations


def update_payment_code_prefix(apps, schema_editor):
    Payment = apps.get_model('api', 'Payment')
    # Update any payment codes starting with "PAY" to "LBP"
    for payment in Payment.objects.filter(code__startswith='PAY'):
        payment.code = 'LBP' + payment.code[3:]
        payment.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20260611_1448'),
    ]

    operations = [
        migrations.RunPython(update_payment_code_prefix),
    ]
