# Generated by Django 6.0.6 on 2026-06-19 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_material_minimum_quantity_notification'),
    ]

    operations = [
    ]
