# Generated by Django 6.0.6 on 2026-08-26 23:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_tcsth_additive_rooms_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
