# Generated by Django 6.0.6 on 2026-09-04 08:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_booking_discount_amount_booking_discount_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('booking_type', models.CharField(choices=[('hall', 'Salle'), ('room', 'Chambre')], default='hall', max_length=20)),
                ('customer_kind', models.CharField(choices=[('individual', 'Particulier'), ('organization', 'Organisation')], default='individual', max_length=20)),
                ('room_ids', models.JSONField(blank=True, default=list)),
                ('organization_name', models.CharField(blank=True, default='', max_length=150)),
                ('organization_contact_name', models.CharField(blank=True, default='', max_length=120)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30)),
                ('guest_full_name', models.CharField(blank=True, default='', max_length=120)),
                ('guest_id_type', models.CharField(blank=True, default='', max_length=30)),
                ('guest_id_number', models.CharField(blank=True, default='', max_length=60)),
                ('event_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_reason', models.CharField(blank=True, default='', max_length=255)),
                ('addons_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tva_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6)),
                ('tva_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('additional_services_selected', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('converted', 'Converti'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_source', to='api.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proformas', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas', to='api.customer')),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hall')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_proformas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
